-- Luna Phase 2 foundation. Master Sections 5, 25, 32-36 are authoritative.
-- No client table writes are granted for server-owned state.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname varchar(30),
  account_status text not null default 'active' check (account_status in ('active', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_active_at timestamptz not null default now(),
  check (nickname is null or (length(nickname) <= 30 and nickname !~ '[\u0000-\u001F\u007F]'))
);

create table if not exists public.user_entry_records (
  user_id uuid primary key references auth.users(id) on delete cascade,
  age_14_plus_attested_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.legal_documents (
  id uuid primary key default gen_random_uuid(),
  document_type text not null,
  version text not null,
  status text not null check (status in ('draft', 'active', 'retired')),
  title text not null,
  public_url text not null,
  interaction text not null check (interaction in ('acceptance_required', 'consent_required', 'notice_only', 'link_only')),
  required_for_registration boolean not null default false,
  required_for_ai boolean not null default false,
  withdrawable boolean not null default false,
  provider_set_version text,
  content_sha256 text,
  effective_at timestamptz,
  created_at timestamptz not null default now(),
  unique (document_type, version),
  check (public_url ~ '^https://'),
  check (not withdrawable or interaction = 'consent_required')
);

create table if not exists public.user_consent_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legal_document_id uuid not null references public.legal_documents(id),
  action text not null check (action in ('accepted', 'withdrawn')),
  event_at timestamptz not null default now(),
  source text not null check (source in ('app', 'web'))
);

create index if not exists user_consent_events_current_idx
  on public.user_consent_events (user_id, legal_document_id, event_at desc, id desc);

create table if not exists public.privacy_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  analytics_enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.birth_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  calendar_type text not null check (calendar_type in ('solar', 'lunar')),
  is_leap_month boolean not null default false,
  birth_date date not null,
  birth_time time,
  birth_time_precision text not null check (birth_time_precision in ('exact', 'approximate', 'unknown')),
  birth_country_code char(2) not null check (birth_country_code ~ '^[A-Z]{2}$'),
  birth_city varchar(80) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (birth_time_precision <> 'unknown' or birth_time is null),
  check (birth_time_precision = 'unknown' or birth_time is not null),
  check (calendar_type <> 'solar' or is_leap_month = false),
  check (birth_city !~ '[\u0000-\u001F\u007F]' and birth_city !~* '(https?://|www\.)')
);

create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default false,
  notification_time time not null default '08:00',
  prompt_status text not null default 'never_asked' check (prompt_status in ('never_asked', 'enabled', 'declined')),
  updated_at timestamptz not null default now()
);

create table if not exists public.fortune_passes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  source text not null check (source in ('fulfillment_missed', 'admin', 'promotion')),
  status text not null check (status in ('available', 'reserved', 'redeemed', 'expired')),
  valid_from_fortune_date date not null,
  expires_after_fortune_date date not null,
  reserved_for_session_id uuid,
  reserved_at timestamptz,
  redeemed_at timestamptz,
  redeemed_fortune_date date,
  source_session_id uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_after_fortune_date >= valid_from_fortune_date)
);

create table if not exists public.daily_fortune_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  fortune_date date not null,
  generation_status text not null default 'not_started' check (generation_status in ('not_started', 'generating', 'recovery_pending', 'ready', 'failed')),
  entitlement_status text not null default 'none' check (entitlement_status in ('none', 'earned_reward', 'earned_pass')),
  entitlement_pass_id uuid references public.fortune_passes(id),
  provider_request_count integer not null default 0 check (provider_request_count >= 0),
  recovery_round_count integer not null default 0 check (recovery_round_count >= 0),
  next_retry_at timestamptz,
  generation_epoch bigint not null default 0 check (generation_epoch >= 0),
  generation_lease_until timestamptz,
  generation_request_id uuid unique,
  provider_set_version text not null default 'dev-mock-v1',
  prompt_version text not null default 'dev-prompt-v1',
  successful_provider_id text,
  successful_model_name text,
  provider_request_id text,
  last_provider_error_class text,
  generation_input_snapshot jsonb,
  fortune_payload jsonb,
  active_ad_attempt_id uuid,
  active_ad_lease_until timestamptz,
  generated_at timestamptz,
  generation_started_at timestamptz,
  last_generation_failure_at timestamptz,
  fulfillment_missed_at timestamptz,
  missed_reason text,
  goodwill_compensation_status text not null default 'none' check (goodwill_compensation_status in ('none', 'issued', 'skipped_cap', 'not_applicable')),
  goodwill_compensation_pass_id uuid references public.fortune_passes(id),
  expires_at timestamptz not null,
  metadata_delete_after timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, fortune_date),
  check (entitlement_status = 'earned_pass' or entitlement_pass_id is null),
  check (generation_status <> 'ready' or fortune_payload is not null)
);

create table if not exists public.ad_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid not null references public.daily_fortune_sessions(id) on delete cascade,
  fortune_date date not null,
  prepare_request_id uuid not null unique,
  challenge_hash text not null unique,
  display_status text not null default 'prepared' check (display_status in ('prepared', 'impression', 'dismissed', 'show_failed')),
  reward_status text not null default 'none' check (reward_status in ('none', 'client_claimed', 'ssv_verified')),
  client_impression_at timestamptz,
  client_reward_claimed_at timestamptz,
  ssv_rewarded_at timestamptz,
  ssv_verified_at timestamptz,
  transaction_id text,
  ad_unit_id text,
  reward_item text,
  reward_amount numeric,
  invalid_ssv_count integer not null default 0,
  last_invalid_ssv_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create unique index if not exists ad_attempts_transaction_unique
  on public.ad_attempts(transaction_id) where transaction_id is not null;

create table if not exists public.ai_provider_sets (
  version text primary key,
  status text not null check (status in ('draft', 'active', 'retired')),
  provider_ids jsonb not null,
  created_at timestamptz not null default now(),
  activated_at timestamptz
);

create table if not exists public.prompt_versions (
  version text primary key,
  status text not null check (status in ('draft', 'active', 'retired')),
  prompt_contract text not null,
  output_schema_version text not null,
  created_at timestamptz not null default now(),
  activated_at timestamptz,
  retired_at timestamptz
);

create table if not exists public.ai_generation_attempts (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.daily_fortune_sessions(id) on delete cascade,
  generation_epoch bigint not null,
  attempt_ordinal integer not null,
  provider_id text not null,
  model_name text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  outcome text not null,
  normalized_error_class text,
  provider_request_id text,
  input_tokens integer,
  output_tokens integer,
  estimated_cost_micros bigint not null default 0
);

create table if not exists public.ai_budget_daily (
  usage_date date primary key,
  reserved_requests integer not null default 0,
  completed_requests integer not null default 0,
  estimated_cost_micros bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_usage_daily (
  usage_date date not null,
  provider_id text not null,
  model_name text,
  prompt_version text not null,
  request_count integer not null default 0,
  success_count integer not null default 0,
  failure_count integer not null default 0,
  input_tokens integer,
  output_tokens integer,
  estimated_cost_micros bigint not null default 0,
  primary key (usage_date, provider_id, model_name, prompt_version)
);

create or replace function public.get_current_fortune_date(now_timestamptz timestamptz default now())
returns date language sql stable as $$
  select ((now_timestamptz at time zone 'Asia/Seoul') - interval '4 hours')::date;
$$;

create or replace function public.is_fortune_transition_window(now_timestamptz timestamptz default now())
returns boolean language sql stable as $$
  select ((now_timestamptz at time zone 'Asia/Seoul')::time >= time '03:55'
    and (now_timestamptz at time zone 'Asia/Seoul')::time < time '04:00');
$$;

create or replace function public.get_fortune_day_expires_at(fortune_day date)
returns timestamptz language sql immutable as $$
  select ((fortune_day + 1)::timestamp + time '03:59:59.999999') at time zone 'Asia/Seoul';
$$;

create or replace function public.get_my_app_state()
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare
  current_user_id uuid := auth.uid();
  now_value timestamptz := now();
  current_day date := public.get_current_fortune_date(now_value);
  current_session public.daily_fortune_sessions%rowtype;
  current_profile public.profiles%rowtype;
  required_registration_count integer;
  accepted_registration_count integer;
  gate_value text := 'NONE';
  state_value text := 'NO_SESSION';
  readable boolean := false;
begin
  if current_user_id is null then
    return jsonb_build_object('api_contract_version', 1, 'server_now', now_value, 'gate', 'REGISTRATION_REQUIRED', 'fortune_state', 'NO_SESSION');
  end if;

  select * into current_profile from public.profiles where id = current_user_id;
  if current_profile.account_status = 'suspended' then gate_value := 'ACCOUNT_SUSPENDED';
  elsif not exists (select 1 from public.user_entry_records where user_id = current_user_id) then gate_value := 'REGISTRATION_REQUIRED';
  else
    select count(*) into required_registration_count from public.legal_documents where status = 'active' and required_for_registration;
    select count(*) into accepted_registration_count
      from public.legal_documents d
      where d.status = 'active' and d.required_for_registration
        and exists (select 1 from public.user_consent_events e where e.user_id = current_user_id and e.legal_document_id = d.id and e.action = 'accepted'
          and e.event_at = (select max(e2.event_at) from public.user_consent_events e2 where e2.user_id = current_user_id and e2.legal_document_id = d.id));
    if accepted_registration_count < required_registration_count then gate_value := 'CONSENT_UPDATE_REQUIRED'; end if;
  end if;

  select * into current_session from public.daily_fortune_sessions where user_id = current_user_id and fortune_date = current_day;
  if current_session.id is not null then
    readable := current_session.entitlement_status <> 'none' and current_session.generation_status = 'ready'
      and current_session.fortune_payload is not null and now_value < current_session.expires_at;
    if public.is_fortune_transition_window(now_value) then state_value := 'TRANSITION_WINDOW';
    elsif readable then state_value := 'UNLOCKED';
    elsif current_session.generation_status = 'generating' then state_value := 'GENERATING';
    elsif current_session.generation_status = 'recovery_pending' then state_value := 'RECOVERY_PENDING';
    elsif current_session.generation_status = 'failed' then state_value := 'FAILED';
    elsif current_session.generation_status = 'ready' then state_value := 'READY_LOCKED';
    else state_value := 'LOCKED'; end if;
  elsif public.is_fortune_transition_window(now_value) then state_value := 'TRANSITION_WINDOW'; end if;

  return jsonb_build_object(
    'api_contract_version', 1, 'server_now', now_value, 'gate', gate_value, 'fortune_state', state_value,
    'fortune_date', current_day, 'expires_at', current_session.expires_at,
    'birth_profile_exists', exists(select 1 from public.birth_profiles where user_id = current_user_id),
    'available_pass_count', (select count(*) from public.fortune_passes where user_id = current_user_id and status = 'available' and current_day between valid_from_fortune_date and expires_after_fortune_date),
    'active_pass_count', (select count(*) from public.fortune_passes where user_id = current_user_id and status in ('available', 'reserved')),
    'can_prepare_rewarded_ad', gate_value = 'NONE' and not readable and not public.is_fortune_transition_window(now_value),
    'can_use_pass', gate_value = 'NONE' and not readable and not public.is_fortune_transition_window(now_value)
      and exists(select 1 from public.fortune_passes where user_id = current_user_id and status = 'available' and current_day between valid_from_fortune_date and expires_after_fortune_date),
    'next_retry_at', current_session.next_retry_at,
    'fortune_payload', case when readable then current_session.fortune_payload else null end
  );
end;
$$;

create or replace function public.upsert_my_birth_profile(payload jsonb)
returns public.birth_profiles language plpgsql security definer set search_path = public, pg_temp as $$
declare result public.birth_profiles; city_value text;
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED'; end if;
  city_value := btrim(normalize(payload->>'birth_city', NFC));
  if length(city_value) = 0 or length(city_value) > 80 or city_value ~ '[\u0000-\u001F\u007F]' or city_value ~* '(https?://|www\.)' or city_value ~ '[\r\n]' then raise exception 'INVALID_BIRTH_CITY'; end if;
  if payload->>'calendar_type' not in ('solar', 'lunar') then raise exception 'INVALID_CALENDAR_TYPE'; end if;
  if payload->>'birth_time_precision' = 'unknown' then payload := jsonb_set(payload, '{birth_time}', 'null'::jsonb); end if;
  if payload->>'birth_time_precision' <> 'unknown' and payload->>'birth_time' is null then raise exception 'BIRTH_TIME_REQUIRED'; end if;
  insert into public.birth_profiles(user_id, calendar_type, is_leap_month, birth_date, birth_time, birth_time_precision, birth_country_code, birth_city)
  values (auth.uid(), payload->>'calendar_type', coalesce((payload->>'is_leap_month')::boolean, false), (payload->>'birth_date')::date, (payload->>'birth_time')::time, payload->>'birth_time_precision', upper(payload->>'birth_country_code'), city_value)
  on conflict (user_id) do update set calendar_type = excluded.calendar_type, is_leap_month = excluded.is_leap_month, birth_date = excluded.birth_date, birth_time = excluded.birth_time, birth_time_precision = excluded.birth_time_precision, birth_country_code = excluded.birth_country_code, birth_city = excluded.birth_city, updated_at = now()
  returning * into result;
  return result;
end;
$$;

create or replace function public.set_my_profile(nickname_value text)
returns public.profiles language plpgsql security definer set search_path = public, pg_temp as $$
declare result public.profiles; clean_name text;
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED'; end if;
  clean_name := nullif(btrim(normalize(nickname_value, NFC)), '');
  if clean_name is not null and (length(clean_name) > 30 or clean_name ~ '[\u0000-\u001F\u007F]' or clean_name ~ '[\r\n]') then raise exception 'INVALID_NICKNAME'; end if;
  insert into public.profiles(id, nickname) values (auth.uid(), clean_name)
  on conflict (id) do update set nickname = excluded.nickname, updated_at = now(), last_active_at = now()
  returning * into result;
  return result;
end;
$$;

create or replace function public.set_my_privacy_preferences(analytics_enabled_value boolean)
returns public.privacy_preferences language plpgsql security definer set search_path = public, pg_temp as $$
declare result public.privacy_preferences;
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED'; end if;
  insert into public.privacy_preferences(user_id, analytics_enabled) values (auth.uid(), coalesce(analytics_enabled_value, false))
  on conflict (user_id) do update set analytics_enabled = excluded.analytics_enabled, updated_at = now()
  returning * into result;
  return result;
end;
$$;

create or replace function public.set_my_notification_preferences(enabled_value boolean, notification_time_value time, prompt_status_value text)
returns public.notification_preferences language plpgsql security definer set search_path = public, pg_temp as $$
declare result public.notification_preferences;
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED'; end if;
  if prompt_status_value not in ('never_asked', 'enabled', 'declined') then raise exception 'INVALID_PROMPT_STATUS'; end if;
  insert into public.notification_preferences(user_id, enabled, notification_time, prompt_status)
  values (auth.uid(), coalesce(enabled_value, false), coalesce(notification_time_value, time '08:00'), prompt_status_value)
  on conflict (user_id) do update set enabled = excluded.enabled, notification_time = excluded.notification_time, prompt_status = excluded.prompt_status, updated_at = now()
  returning * into result;
  return result;
end;
$$;

create or replace function public.record_my_consent_event(document_id uuid, action_value text)
returns public.user_consent_events language plpgsql security definer set search_path = public, pg_temp as $$
declare document_row public.legal_documents; result public.user_consent_events;
begin
  if auth.uid() is null then raise exception 'UNAUTHENTICATED'; end if;
  select * into document_row from public.legal_documents where id = document_id and status = 'active';
  if document_row.id is null then raise exception 'LEGAL_DOCUMENT_NOT_ACTIVE'; end if;
  if action_value not in ('accepted', 'withdrawn') then raise exception 'INVALID_CONSENT_ACTION'; end if;
  if action_value = 'withdrawn' and not document_row.withdrawable then raise exception 'CONSENT_NOT_WITHDRAWABLE'; end if;
  insert into public.user_consent_events(user_id, legal_document_id, action, source)
  values (auth.uid(), document_row.id, action_value, 'app') returning * into result;
  return result;
end;
$$;

alter table public.profiles enable row level security;
alter table public.user_entry_records enable row level security;
alter table public.legal_documents enable row level security;
alter table public.user_consent_events enable row level security;
alter table public.privacy_preferences enable row level security;
alter table public.birth_profiles enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.fortune_passes enable row level security;
alter table public.daily_fortune_sessions enable row level security;
alter table public.ad_attempts enable row level security;
alter table public.ai_provider_sets enable row level security;
alter table public.prompt_versions enable row level security;
alter table public.ai_generation_attempts enable row level security;
alter table public.ai_budget_daily enable row level security;
alter table public.ai_usage_daily enable row level security;

create policy profiles_select_own on public.profiles for select to authenticated using (id = auth.uid());
create policy birth_profiles_select_own on public.birth_profiles for select to authenticated using (user_id = auth.uid());
create policy notification_preferences_select_own on public.notification_preferences for select to authenticated using (user_id = auth.uid());
create policy privacy_preferences_select_own on public.privacy_preferences for select to authenticated using (user_id = auth.uid());
create policy fortune_passes_select_own on public.fortune_passes for select to authenticated using (user_id = auth.uid());
create policy legal_documents_select_active on public.legal_documents for select to anon, authenticated using (status = 'active');

revoke all on table public.user_entry_records, public.user_consent_events, public.daily_fortune_sessions, public.ad_attempts, public.ai_provider_sets, public.prompt_versions, public.ai_generation_attempts, public.ai_budget_daily, public.ai_usage_daily from anon, authenticated;
revoke insert, update, delete on table public.profiles, public.birth_profiles, public.notification_preferences, public.privacy_preferences, public.fortune_passes from anon, authenticated;
revoke all on function public.get_my_app_state() from public, anon;
grant execute on function public.get_my_app_state() to authenticated;
revoke all on function public.upsert_my_birth_profile(jsonb) from public, anon;
grant execute on function public.upsert_my_birth_profile(jsonb) to authenticated;
revoke all on function public.set_my_profile(text) from public, anon;
grant execute on function public.set_my_profile(text) to authenticated;
revoke all on function public.set_my_privacy_preferences(boolean) from public, anon;
grant execute on function public.set_my_privacy_preferences(boolean) to authenticated;
revoke all on function public.set_my_notification_preferences(boolean, time, text) from public, anon;
grant execute on function public.set_my_notification_preferences(boolean, time, text) to authenticated;
revoke all on function public.record_my_consent_event(uuid, text) from public, anon;
grant execute on function public.record_my_consent_event(uuid, text) to authenticated;
